repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: tests/data
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: file-contents-sorter
        files: requirements-dev.txt

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: docs/source/conf.py
        args: [--ignore-missing-imports]
        additional_dependencies:
          - types-PyYAML

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --quiet-level=2

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.11"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
